@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.limonblaze.originsclasses.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;