@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package limonblaze.originsclasses.util;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;