@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package limonblaze.originsclasses.common.apoli.power;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;